project:
  type: website
  output-dir: docs
  
website:
  title: "Damage Benchmark"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - benchmark.qmd
      - data.qmd
      - results.qmd
      - contribute.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/AlicenJoyHenning/Damage-Benchmark
          - text: Report a Bug
            href:  https://github.com/AlicenJoyHenning/Damage-Benchmark/issues

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: minty

editor: source

execute:
  echo: true
  warning: false
  error: true

